# POST http://localhost:3001/api/persons
# Content-Type: application/json

POST https://phonebook-backend-tlsr.onrender.com/api/persons
Content-Type: application/json

{
  "name": "John Doe",
  "number":"1234567889111"
}